steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/devops-project-465603", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/devops-project-465603"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/devops-project-465603/${BUILD_ID}
  - --location=us-central1-a
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod
options:
  logging: CLOUD_LOGGING_ONLY